### PR TITLE
Add category controller

### PR DESCRIPTION
**Pull request by ifalatik**
I added a controller for firewall categories.

I used a different design than what was used previously for the other controllers. Major differences are:
- Create a Category class instead of using dictionaries. This is more object oriented, and improves readability.
- This class inherits from pydantics BaseModel. This allows for easier transitions between json/dict and object, and easy field validation.
- Thus I named my controller CategoryController, instead of Category

I had to bump python to 3.9 to allow for quick and easy dictionary combination (category_controller.py, l. 63)

I believe that if we switch the other controllers to this model, we will have an overall cleaner project. I'd aim to have the controllers inherit from a separate controller class, to reduce code duplication.

### CODE REVIEW

**Comment by dylanturn** [comment]
This is awesome, thank you for the contribution!  I'm going to take a closer look at this in the morning, I'm a bit short on time right now and my brain is fried.

**Comment by ifalatik** [comment]
If you want me to refactor the other controllers to match this approach I can send you a PR for that too. Would probably be able to do it this weekend.

Or I can include it in this PR if you prefer.

**Comment by dylanturn** [comment]
Before we refactor everything, I wanted to present something very similar that I had been working on. I pushed my changes to a feature branch of my fork. [Here's a link](https://github.com/turnbros/python-opnsense/compare/main...dylanturn:python-opnsense:feature/generics?expand=1)

My approach was to use generics so we could avoid having to re-implement list, get, and delete actions for each module and controller while also making it easy to implement other actions. It would also make it easy to normalize the API by creating controllers based on models organized by module, rather than the mess it is today. Overall, the approach is similar to what I did for unbound, just taken a bit further.

The only other real difference is where the API response is being parsed. I had tried to do something inline with what you did and implement the parser as an abstract class method, but Python insisted that while it totally knew what 'T' was and that it definitely had a parse method, any time I tried to access that parse method at run time I'd be met with a ` 'TypeVar' object has no attribute` error....so I gave up and made it an abstract method within the controller since we're going to end up with a 1:1 controller to model ratio anyway...

That said, the approach I'm proposing doesn't handle validation very well and I think could be improved by having the base `OPNsenseItem` extend `pydantic.BaseModel`. Usability of this library is important to me, being able to catch bad inputs and return errors quickly is critical.

I'm really interested to hear your thoughts on this.
Thanks!

**Comment by ifalatik** [comment]
I think using generics would probably have been part of my refactoring as well. I looked at the way you implemented it, and I like the approach. If we were to use this, I believe having `OPNSenseItem` extend `pydantic.BaseModel` would result in the best readability and extensibility for new controllers and items.

One caveat I could see come up is controllers and items being handled the same **across** modules. We might want to have different "ready to go" controllers in `item_controller(s).py` at some point, where we would just need to instantiate it with a dataclass typevar.

I'd like to see you push this branch into a feature branch here, so I help with the other modules. I also stumbled across some bugs / code smells I'd like to improve before pushing to main.

On a different note, could we use PEP8 conform code styles? My IDEs keep screaming at me because of 2 spaces instead of 4.

**Comment by ifalatik** [comment]
I turned this to a draft PR, so we can refactor everything nicely before merging.

**Comment by dylanturn** [comment]
> ...could we use PEP8 conform code styles? My IDEs keep screaming at me because of 2 spaces instead of 4.

Fiiiiiiine! I got around that issue by convincing my IDE that what we really wanted was 2 spaces 🤭, but I suppose it's probably for the best that I conform. I've merged the changes you proposed in `Feature/code cleanup`. Thanks again for your contribution!

> I'd like to see you push this branch into a feature branch here, so I help with the other modules. I also stumbled across some bugs / code smells I'd like to improve before pushing to main.

Makes sense. I'll sync my forks feature branch with `main` and then push it to a new branch called `develop`. Does that work?

> One caveat I could see come up is controllers and items being handled the same across modules. We might want to have different "ready to go" controllers in item_controller(s).py at some point, where we would just need to instantiate it with a dataclass typevar.

I think I might know what you mean, but any chance you have an example?

Let me know if this is what you were thinking or if I'm way off:

I was thinking that in addition to having `item_controller.py` that defines a generic controller class with the usual CRUD-ish methods, we could also have something like `item_controller_shards.py` that contains classes with signatures similar to `OPNsenseItemController` and each class would implement a specific OPNsense API action-verb.

Here's an example:

This is the Item Controller in `item_controller.py`:
```python
class OPNsenseItemController(Generic[T], OPNsenseAPIController):
    def apply(self) -> None:
        pass
    def list(self) -> List[T]:
        pass
    def get(self, uuid: str) -> T:
        pass
    def delete(self, item: T) -> None:
        pass
    @abstractmethod
    def add(self, item: T) -> T:
        pass
    @abstractmethod
    def set(self, item: T) -> T:
        pass
```

And this would be an Item Controller Shard in `item_controller_shards.py` that implements the toggle API action:
```python
# Please excuse the Java sized class names
class OPNsenseItemControllerToggleShard(Generic[T], OPNsenseAPIController):
    def toggle(self, item: T) -> T:
        pass
```

Implementing the extra verbs as "shards" allows us to compose the controllers that are ultimately used by "end users" (Note: I have no idea how to classify those controllers):
```python
# Note: I'm using the Firewall Filter as an example
class FilterController(OPNsenseItemController[Filter], OPNsenseItemControllerToggleShard[Filter]):
    def add(self, item: T) -> T:
        pass
    def set(self, item: T) -> T:
        pass
```

I should note, this is all purely theoretical. I don't have some secret branch where I've tried any of this.

**Comment by dylanturn** [comment]
Ok, all done, though the tests are angry now. I'd dig into it a bit more, but my laptop is out for repairs at the moment and I'm finding development on my gaming PC to be a somewhat frustrating experience.

Should have my laptop back within the next couple days.... 🤞

**Comment by dylanturn** [comment]
Ok, we did it! All your refactoring changes have been merged in, and I got develop to pass the tests: https://github.com/turnbros/python-opnsense/actions/runs/4229287097/jobs/7345527563

Which isn't to say the tests are a masterpiece, but they're not nothing. 

Right now all PRs run again the main branch. this seems fairly pointless, but unfortunately Github won't pass secrets to actions being run against code from public forks.....something about security concerns. Looks like I'll have to come up with a better solution...

**Comment by ifalatik** [comment]
Awesome, thanks! I'm currently working on a big refactoring of the existing controllers, to match the new approach. I've already come across some special cases, which I'm trying to find a good solution for. I'll send a PR once I have something that works👍🏼.

**Comment by dylanturn** [comment]
Fantastic, thank you! I'll keep working on isolating the testing infra so we can run the tests against proposed changes.

I also got my laptop back, so I'm ready to rock and/or roll!

**Comment by dylanturn** [comment]
I saw an merged your other PR. I also updated the filter controller in main and now the tests pass on `main`.

For the sake of simplifying the code base and making things easier to refactor, I'm going to create and publish release `1.0.5` so that we can ditch the deprecated methods and focus on version 1.1.0.

**Pull request closed without merging**
